# Z-shell configuration
# bernard.elhagin@gmail.com
# https://github.com/bernard-elhagin/dots

source ~/.zsh/base.zsh
source ~/.zsh/colors.zsh
source ~/.zsh/keybindings.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/integrations.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
